char * str_tok(char *string, char *such);
void str_cpy(char *dest,char *src);
int str_isdigit(char *string);
void str_remblanks(char *ptr);
void str_remleadblanks(char *ptr);
void str_nfill(char *help,int zeichen,int anzahl);
void str_filln(char *help,int zeichen,int anzahl);
void str_cpyback(char *dest, char *src);
int str_searchchar(char *zeichenkette,char zeichen);
void str_upr(char *string);
int str_ncmp(char *str1, char *str2, int anz);
void str_ins(char *str, char *ins);
int str_delchar(char *str, int pos);
int str_len(char *str);
int str_cat(char *str, char *str1);
int str_search(char *zeichenkette,char zeichen);
void str_RemoveEmptyLines(char *buff);
int str_GetLine(char *ret, char *buff);
void str_RemTrailBlanks(char *ptr);
int str_cmp(char *str1, char *str2);
int str_isHexDigit(char zeichen);
int str_IsHexString(char *buff);
void str_DelLine(char *str);
int str_HasStringAlpha( char *str);
void str_center(char *ptr);
void str_vtx_convert(unsigned char *ptr);
char str_umlaute_VtxToWin(char zeichen);
long str_isTime(char *time);
void str_remblanks_spez(char *ptr);
void str_WinToVtx(char *str);
char str_umlaute_WinToVtx(char zeichen);
int str_FindStrBack(char * str,char *search,int RxIdx);

void str_GetUhrzeit(char *str);
